### PR TITLE
Fix %20 showing in title and displays the space correctly

### PR DESCRIPTION
**Pull request by tkrn**

### CODE REVIEW

**Comment by glen-cheney** [comment]
Can you give me an example URL where this solution is needed?

**Comment by tkrn** [comment]
Sure thing. Here is the fix on my website. The folder on the file system naturally has a space in it since URL are encoded it's get encoded to %20 but I wouldn't consider that a 'human friendly' title. I'm sure they are other encodings that should get addressed to

http://nthnk.com/u/cmb69/FFXI%20Screenshots/

**Comment by glen-cheney** [comment]
`decodeURI` already decodes the `%20` to a space. Maybe you were using an older version of fancy-index which didn't have it?

If I set a breakpoint in the `script.js` in your screenshots folder, I can see that `newstr` correctly decodes the space before you call `.replace()` on it.

**Comment by tkrn** [comment]
You are correct. It must have been an old version of script.js. Closing pull request.

**Comment by glen-cheney** [comment]
Thanks for the contribution though!

**Pull request closed without merging**
